title:            Nikhil Prakash
description:      Nikhil Prakash's Academic Website
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://nix07.github.io

# Owner/author information
owner:
  name:           Nikhil Prakash
  avatar:         Pic.jpg
  bio:            I'm a senior undergraduate student from RV College of Engineering, Bangalore, India. Aspire to become an awesome researcher!
  email:          nikhil07prakash@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: nikhil07prakash
  # google_scholar: RG1EQowAAAAJ
  github: nix07
  linkedin: nikhil07prakash
  instagram: nix.prakash
# Analytics and webmaster tools stuff goes here
# google_analytics: UA-19657956-3
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: "/"
  - title: CV
    url: "https://docs.google.com/document/d/1Cu_lgiqYNxroby96rOMojizwu59w29xSTL14Zoy7iek/edit?usp=sharing"
    external: true
  - title: Publications
    url: "/publications/"
  - title: Blog Posts
    url: "https://medium.com/@nikhil07prakash"
    external: true
  # - title: Resources
  #   url: /resources/
  # - title: Fun
  #   url: /fun/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    India/Kolkata
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  enable_coderay: false

#  coderay:
#    coderay_line_numbers:
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]
